# SwiftLint Configuration for SwiftSecuencia
# Enforces macOS 26.0+ and iOS 26.0+ minimum deployment targets

excluded:
  - .build
  - DerivedData
  - .swiftpm
  - Tests/SwiftSecuenciaTests/Resources
  - Sources/Pipeline  # Third-party code from Pipeline library

# Disabled rules (to focus on platform enforcement, not code style)
disabled_rules:
  - identifier_name
  - force_cast
  - trailing_comma
  - redundant_string_enum_value
  - function_parameter_count
  - function_body_length
  - type_body_length
  - file_length
  - line_length
  - cyclomatic_complexity
  - for_where
  - shorthand_operator

opt_in_rules:
  - unavailable_function

custom_rules:
  # Prevent @available with macOS versions < 26
  # Matches: @available(macOS 15.0, *), @available(macOS, introduced: 15.0), @available(iOS 25, macOS 15.0, *)
  no_old_macos_availability_attribute:
    regex: '@available\s*\([^)]*macOS\s*(?:,\s*introduced:\s*)?\b([0-9]|1[0-9]|2[0-5])\b(?:\.[0-9]+)?'
    match_kinds:
      - attribute.builtin
    message: "Use @available(macOS 26.0, *) or higher. macOS versions < 26 are not supported."
    severity: error

  # Prevent #available with macOS versions < 26
  # Matches: #available(macOS 15, *), #available(macOS, introduced: 15.0), #available(iOS 25, macOS 15, *)
  no_old_macos_availability_check:
    regex: '#available\s*\([^)]*macOS\s*(?:,\s*introduced:\s*)?\b([0-9]|1[0-9]|2[0-5])\b(?:\.[0-9]+)?'
    message: "Use #available(macOS 26, *) or higher. macOS versions < 26 are not supported."
    severity: error

  # Prevent #unavailable with macOS versions < 26
  # Matches: #unavailable(macOS 15), #unavailable(macOS, introduced: 15.0), #unavailable(iOS 25, macOS 15)
  no_old_macos_unavailability_check:
    regex: '#unavailable\s*\([^)]*macOS\s*(?:,\s*introduced:\s*)?\b([0-9]|1[0-9]|2[0-5])\b(?:\.[0-9]+)?'
    message: "Use #unavailable(macOS 26, *) or higher. macOS versions < 26 are not supported."
    severity: error

  # Prevent iOS versions < 26.0
  no_old_ios_availability_attribute:
    regex: "@available\\s*\\([^)]*iOS\\s*(?:,\\s*introduced:\\s*)?\\b([0-9]|1[0-9]|2[0-5])\\b(?:\\.[0-9]+)?"
    match_kinds:
      - attribute.builtin
    message: "Use @available(iOS 26.0, *) or higher. iOS versions < 26 are not supported."
    severity: error

  # Prevent #available with iOS versions < 26
  no_old_ios_availability_check:
    regex: "#available\\s*\\([^)]*iOS\\s*(?:,\\s*introduced:\\s*)?\\b([0-9]|1[0-9]|2[0-5])\\b(?:\\.[0-9]+)?"
    message: "Use #available(iOS 26, *) or higher. iOS versions < 26 are not supported."
    severity: error

  # Prevent #unavailable with iOS versions < 26
  no_old_ios_unavailability_check:
    regex: "#unavailable\\s*\\([^)]*iOS\\s*(?:,\\s*introduced:\\s*)?\\b([0-9]|1[0-9]|2[0-5])\\b(?:\\.[0-9]+)?"
    message: "Use #unavailable(iOS 26, *) or higher. iOS versions < 26 are not supported."
    severity: error
